POST localhost:8080/participants
content-type: application/json

{
	"name": "edu",
	"phone": "(11)3482948249238",
	"address": {
		"number": "101",
		"district": "teucu",
		"street": "macarrão"
	},
	"maritalStatus": "SINGLE",
	"cpf" : "929292929-42"
}

###

GET localhost:8080/participants

### 

DELETE localhost:8080/participants/1
